### ISSUE TITLE
Custom Yolov8 model

### ISSUE THREAD

**Issue by elfar** [insight-platform/Savant#457] opened 2023-09-27 13:29 UTC
Hi, I was wondering if anybody had successfully tried bringing their own yolov8 model into the traffic_meter sample?

I tried with .pt weights with both yolov8m and yolov8s models. My process was

1) Export weights as onnx: yolo export model=mymodel.pt --format=onnx
2) Replace models/traffic_meter/yolov8m/yolov8m.onnx with mymodel.onnx but keeping original name
3) Adjust labels.txt with my one class and change num-detected-classes=80 to num-detected-classes=1 in config
4) Run docker-compose again (it worked fine with the provided Savant test model)

The traffic_meter module creates the engine file but when it tries to start using it the container crashes with code 139. The log is below. One interesting difference between the Savant yolo8m model and mymodel is that Savant model has 4 layers compared to my 2:

INFO: [Implicit Engine Info]: layers num: 4
0   INPUT  kFLOAT input           3x640x640       
1   OUTPUT kFLOAT boxes           8400x4          
2   OUTPUT kFLOAT scores          8400x1          
3   OUTPUT kFLOAT classes         8400x1   

vs

INFO: [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT images          3x640x640       
1   OUTPUT kFLOAT output0         5x8400          

How is the onnx used in savant created? Am I missing some config change some place with my new, only 1 class model?

Docker traffic_meter_module log:

 INFO  insight::savant::gstreamer::runner                   > Received EOS from pipeline0.
 INFO  insight::savant::gstreamer::runner                   > The pipeline is about to stop. Operation took 0:01:35.600607.
 INFO  insight::savant::deepstream::encoding                > Encoder for codec 'h264' is available
 INFO  insight::savant::deepstream::utils::pipeline         > No telemetry provider specified. Using noop tracer.
 INFO  insight::savant::traffic_meter-yolov8m               > Pipeline frame processing parameters: {'width': 1280, 'height': 900, 'batch-size': 1, 'buffer-pool-size': 4, 'batched-push-timeout': 2000, 'live-source': False, 'interpolation-method': 6, 'drop-pipeline-eos': True}.
 INFO  insight::savant::gstreamer::runner                   > Starting pipeline `traffic_meter-yolov8m<NvDsPipeline>: zeromq_source_bin:v1(name=source) -> nvstreammux:v1(name=muxer) -> pyfunc:v1(name=pyfunc+gstpluginpyfunc0) -> nvinfer@detector:v1(name=yolov8m) -> nvtracker:v1(name=nvtracker0) -> pyfunc:v1(name=pyfunc+gstpluginpyfunc1) -> pyfunc:v1(name=pyfunc+gstpluginpyfunc2) -> nvstreamdemux:v1(name=demuxer)`...
 INFO  insight::savant::healthcheck::status                 > Setting module status to ModuleStatus.STARTING.
gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
[NvMultiObjectTracker] Initialized
0:01:50.852184924     1      0xb353a10 INFO                 nvinfer gstnvinfer.cpp:682:gst_nvinfer_logger:<yolov8m> NvDsInferContext[UID 2]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1988> [UID = 2]: deserialized trt engine from :/models/yolov8m/model_b1_gpu0_fp16.engine
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
INFO: [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT images          3x640x640       
1   OUTPUT kFLOAT output0         5x8400          

0:01:51.028996066     1      0xb353a10 INFO                 nvinfer gstnvinfer.cpp:682:gst_nvinfer_logger:<yolov8m> NvDsInferContext[UID 2]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2091> [UID = 2]: Use deserialized engine model: /models/yolov8m/model_b1_gpu0_fp16.engine
0:01:51.497449471     1      0xb353a10 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<yolov8m> [UID 2]: Load new model:/models/yolov8m/model_b1_gpu0_fp16_config_savant.txt sucessfully
 INFO  insight::savant::utils::zeromq                       > Starting ZMQ source: socket ipc:///tmp/zmq-sockets/input-video.ipc, type ReceiverSocketTypes.SUB, bind True.
 INFO  insight::savant::gstreamer::runner                   > The pipeline is initialized and ready to process data. Initialization took 0:00:04.668293.
 INFO  insight::savant::healthcheck::status                 > Setting module status to ModuleStatus.RUNNING.
 INFO  insight::savant::savant_rs_video_decode_bin          > Adding branch with source town-centre-processed
 INFO  insight::savant::savant_rs_video_decode_bin          > Branch with source town-centre-processed added
 INFO  insight::savant::savant_rs_video_demux               > Created new src pad for source town-centre-processed: src_town-centre-processed.
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NvMMLiteBlockCreate : Block : BlockType = 261 
Opening in BLOCKING MODE 
 INFO  insight::savant::traffic_meter-yolov8m               > Added source town-centre-processed
NvMMLiteOpen : Block : BlockType = 4 
===== NvVideo: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4

**Comment by bwsw** [comment] 2023-09-27 13:34
@elfar 
you'd better ask in Discord https://discord.gg/KVAfGBsZGd

You can see that we use a custom YOLOV8-Face model in the ReID sample and YOLOV8-Seg in yolov8-seg sample. As long as your model is correct and properly specified, it must work.

139 is a segmentation fault. Something wrong happens.

Join Discord and share your archive with model files. We will take a look. I will close the issue as it is not a bug or feature. 

PS: If the model is copyrighted and commercial (you can not share in the public channel) and you need a commercial consultancy, we also help there (with NDA, etc.).

**Closed as completed by bwsw** 2023-09-27 13:34 UTC

**Comment by elfar** [comment] 2023-09-27 13:39
Understood, thank you
